// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RS.Data;
using System;

namespace RS.Data.Migrations
{
    [DbContext(typeof(RSContext))]
    partial class RSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RS.Entity.Models.ApprovalActions", b =>
                {
                    b.Property<int>("ApprovalActionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApprovalActionName");

                    b.Property<int>("ApprovalEventId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.HasKey("ApprovalActionId");

                    b.HasIndex("ApprovalEventId");

                    b.ToTable("ApprovalActions");
                });

            modelBuilder.Entity("RS.Entity.Models.ApprovalEventRoles", b =>
                {
                    b.Property<int>("ApprovalEventRoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApprovalEventId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("RoleId");

                    b.HasKey("ApprovalEventRoleId");

                    b.HasIndex("ApprovalEventId");

                    b.HasIndex("RoleId");

                    b.ToTable("ApprovalEventRoles");
                });

            modelBuilder.Entity("RS.Entity.Models.ApprovalEvents", b =>
                {
                    b.Property<int>("ApprovalEventId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApprovalEventName");

                    b.Property<int>("ApprovalEventOrder");

                    b.Property<int>("ApprovalId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.HasKey("ApprovalEventId");

                    b.HasIndex("ApprovalId");

                    b.ToTable("ApprovalEvents");
                });

            modelBuilder.Entity("RS.Entity.Models.Approvals", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApprovalDesc");

                    b.Property<string>("ApprovalName");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.HasKey("ApprovalId");

                    b.ToTable("Approvals");
                });

            modelBuilder.Entity("RS.Entity.Models.ApprovalTransactionDetails", b =>
                {
                    b.Property<int>("ApprovalTransactionDetailId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApprovalActionId");

                    b.Property<int>("ApprovalEventOrderNumber");

                    b.Property<int>("ApprovalTransactionId");

                    b.Property<string>("Comments");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.HasKey("ApprovalTransactionDetailId");

                    b.HasIndex("ApprovalTransactionId");

                    b.ToTable("ApprovalTransactionDetails");
                });

            modelBuilder.Entity("RS.Entity.Models.ApprovalTransactions", b =>
                {
                    b.Property<int>("ApprovalTransactionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApprovalActionId");

                    b.Property<int>("ApprovalEventOrderNumber");

                    b.Property<int>("ApprovalId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<Guid>("EntityId");

                    b.Property<int>("EntityType");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("NextApprovalEventOrderNumber");

                    b.HasKey("ApprovalTransactionId");

                    b.HasIndex("ApprovalActionId");

                    b.ToTable("ApprovalTransactions");
                });

            modelBuilder.Entity("RS.Entity.Models.Candidate", b =>
                {
                    b.Property<Guid>("CandidateId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CandidateDesc");

                    b.Property<int>("CandidateExperienceMonth");

                    b.Property<int>("CandidateExperienceYear");

                    b.Property<string>("CandidateFirstName");

                    b.Property<int>("CandidateGender");

                    b.Property<string>("CandidateLastName");

                    b.Property<string>("CandidateOrganisation");

                    b.Property<int>("CandidateQualificationId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.HasKey("CandidateId");

                    b.HasIndex("CandidateQualificationId");

                    b.ToTable("Candidate");
                });

            modelBuilder.Entity("RS.Entity.Models.CandidateDocuments", b =>
                {
                    b.Property<Guid>("CandidateDocumentId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CandidateId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("UploadedDocumentName");

                    b.Property<string>("UploadedDocumentPath");

                    b.HasKey("CandidateDocumentId");

                    b.HasIndex("CandidateId");

                    b.ToTable("CandidateDocuments");
                });

            modelBuilder.Entity("RS.Entity.Models.CandidateSkills", b =>
                {
                    b.Property<int>("CandidateSkillId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CandidateId");

                    b.Property<int>("SkillId");

                    b.HasKey("CandidateSkillId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkills");
                });

            modelBuilder.Entity("RS.Entity.Models.Openings", b =>
                {
                    b.Property<Guid>("OpeningId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("OpeningDescription");

                    b.Property<string>("OpeningDetails");

                    b.HasKey("OpeningId");

                    b.ToTable("Openings");
                });

            modelBuilder.Entity("RS.Entity.Models.OpeningSkills", b =>
                {
                    b.Property<int>("OpeningSkillId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("OpeningId");

                    b.Property<int>("SkillId");

                    b.HasKey("OpeningSkillId");

                    b.HasIndex("OpeningId");

                    b.HasIndex("SkillId");

                    b.ToTable("OpeningSkills");
                });

            modelBuilder.Entity("RS.Entity.Models.Qualifications", b =>
                {
                    b.Property<int>("QualificationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("QualificationDesc");

                    b.Property<string>("QualificationName");

                    b.HasKey("QualificationId");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("RS.Entity.Models.Roles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleName");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RS.Entity.Models.Skills", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SkillDescription");

                    b.Property<string>("SkillName");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("RS.Entity.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<string>("Email");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RS.Entity.Models.ApprovalActions", b =>
                {
                    b.HasOne("RS.Entity.Models.ApprovalEvents", "ApprovalEvent")
                        .WithMany("ApprovalActions")
                        .HasForeignKey("ApprovalEventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RS.Entity.Models.ApprovalEventRoles", b =>
                {
                    b.HasOne("RS.Entity.Models.ApprovalEvents", "ApprovalEvent")
                        .WithMany("ApprovalEventRoles")
                        .HasForeignKey("ApprovalEventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RS.Entity.Models.Roles", "Role")
                        .WithMany("ApprovalEventRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RS.Entity.Models.ApprovalEvents", b =>
                {
                    b.HasOne("RS.Entity.Models.Approvals", "Approval")
                        .WithMany()
                        .HasForeignKey("ApprovalId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RS.Entity.Models.ApprovalTransactionDetails", b =>
                {
                    b.HasOne("RS.Entity.Models.ApprovalTransactions")
                        .WithMany("ApprovalTransactionDetails")
                        .HasForeignKey("ApprovalTransactionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RS.Entity.Models.ApprovalTransactions", b =>
                {
                    b.HasOne("RS.Entity.Models.ApprovalActions", "ApprovalAction")
                        .WithMany()
                        .HasForeignKey("ApprovalActionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RS.Entity.Models.Candidate", b =>
                {
                    b.HasOne("RS.Entity.Models.Qualifications", "CandidateQualification")
                        .WithMany("Candidate")
                        .HasForeignKey("CandidateQualificationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RS.Entity.Models.CandidateDocuments", b =>
                {
                    b.HasOne("RS.Entity.Models.Candidate", "Candidate")
                        .WithMany("CandidateDocuments")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RS.Entity.Models.CandidateSkills", b =>
                {
                    b.HasOne("RS.Entity.Models.Candidate", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RS.Entity.Models.Skills", "Skill")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RS.Entity.Models.OpeningSkills", b =>
                {
                    b.HasOne("RS.Entity.Models.Openings", "Opening")
                        .WithMany("OpeningSkills")
                        .HasForeignKey("OpeningId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RS.Entity.Models.Skills", "Skill")
                        .WithMany("OpeningSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
